x-common: &common
  env_file: .env
  restart: unless-stopped

services:
  # smp:
  #   <<: *common
  #   image: itzg/minecraft-server:latest
  #   environment:
  #     PATCH_DEFINITIONS: /patches
  #     TYPE: "PAPER"
  #     ONLINE_MODE: "FALSE"
  #     ENFORCE_SECURE_PROFILE: "FALSE"
  #     NETWORK_COMPRESSION_THRESHOLD: "-1"
  #     INIT_MEMORY: "1G"
  #     MAX_MEMORY: "2G"
  #     USE_AIKAR_FLAGS: "TRUE"
  #   volumes:
  #     - ./smp/patches:/patches:ro
  #     # - ./mnt/smp:/data

  smp:
    <<: *common
    image: itzg/minecraft-server:latest
    environment:
      PATCH_DEFINITIONS: /patches
      TYPE: "FORGE"
      VERSION: "1.20.1"
      ONLINE_MODE: "FALSE"
      ENFORCE_SECURE_PROFILE: "FALSE"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
      USE_AIKAR_FLAGS: "TRUE"
      SYNC_CHUNK_WRITES: "FALSE"
      OPS: |-
        TTQD
      ALLOW_FLIGHT: "TRUE"
    volumes:
      - ./smp/patches:/patches:ro
      - ./mnt/smp:/data
      - ./mods:/mods:ro

  proxy:
    <<: *common
    image: itzg/mc-proxy:latest
    entrypoint: ["/bin/sh", "-c", "mkdir -p /server && printf '%s' \"$$CFG_FORWARDING_SECRET\" > /server/forwarding.secret && exec /__cacert_entrypoint.sh /usr/bin/run-bungeecord.sh"]
    environment:
      PATCH_DEFINITIONS: /patches
      TYPE: "VELOCITY"
      PLUGINS: |-
        https://github.com/SkinsRestorer/SkinsRestorer/releases/latest/download/SkinsRestorer.jar
        https://github.com/TCPShield/RealIP/releases/download/2.8.1/TCPShield-2.8.1.jar
        https://github.com/adde0109/Ambassador/releases/download/v1.4.5/Ambassador-Velocity-1.4.5-all.jar
        https://hangarcdn.papermc.io/plugins/jmp/MiniMOTD/versions/2.2.2/VELOCITY/minimotd-velocity-2.2.2.jar
    volumes:
      - ./proxy/patches:/patches:ro
      - ./proxy/plugins:/plugins:ro
    ports:
      - "${PROXY_PORT}:25577"

  watchtower:
    image: nickfedor/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
